services:
  inbox-arena:
    image: gcr.io/${PROJECT_ID}/inbox-arena
    container_name: inbox-arena-main-prod
    ports:
      - "8000:8000"  # Game server
      - "8002:8002"  # Dashboard
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    # Production-specific settings
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M